// CALENDAR
export const UPCOMING_CALENDAR_VIEW = 'upcoming';
export const WEEKEND_CALENDAR_VIEW = 'weekend';
export const WEEK_CALENDAR_VIEW = 'week';
export const DEFAULT_CALENDAR_VIEW = WEEKEND_CALENDAR_VIEW;

export const CALENDAR_VIEWS = [
  UPCOMING_CALENDAR_VIEW,
  WEEKEND_CALENDAR_VIEW,
  WEEK_CALENDAR_VIEW
] as const;

export const NB_OF_DAYS_BY_VIEWS = {
  [WEEKEND_CALENDAR_VIEW]: 3,
  [WEEK_CALENDAR_VIEW]: 7
} as const;
